source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
inhibit_all_warnings!


target 'SwiftyCompanion' do
    pod 'SwiftyJSON', '~> 2.3'
    pod 'Alamofire'
    pod 'KeychainSwift', '~> 3.0'
end
